# -*- coding: utf-8 -*-
"""HESHICA_PYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKWYqr9yzDO1D_p9jFIRAMp-Jn2ZX1AD
"""

Name="Heshica Battina Chowdary"

Email_id="heshicabattina982@gmail.com"

Slack_username="@Heshica"

Biostack="Drug Development and Genomics"

twitter="@HeshicaBattina"

d=0

if len(Slack_username)>= len(twitter):

  for i in range(len(Slack_username)):
   try:
     if Slack_username[i].lower() != twitter[i].lower():
      d=d+1

   except:
      d=d+1
elif len (twitter)>len(Slack_username):
    for i in range(len(twitter)):
     try:
      if twitter[i].lower() != Slack_username[i].lower():
              d=d+1
     except:
                d=d+1


print("%s,%s,%s,%s,%s,%s "% (Name, Email_id, Slack_username, Biostack,twitter,d))