# -*- coding: utf-8 -*-
"""HESHICA_PYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKWYqr9yzDO1D_p9jFIRAMp-Jn2ZX1AD

*   List item
*   List item

Y5RYTYU5FYRFJU6TU6TUY6UT
"""

Name="Heshica Battina Chowdary"

Email_id="heshicabattina982@gmail.com"

Slack_username="@Heshica"

Biostack="Drug Development and Genomics"

print("%s,%s,%s,%s"% (Name, Email_id, Slack_username, Biostack))